export const FETCH_FIRST_POKEMON = "FETCH_FIRST_POKEMON";
export const FETCH_SECOND_POKEMON = "FETCH_SECOND_POKEMON";
export const INITIAL_CURRENT_HP = "INITIAL_CURRENT_HP";
export const FIRST_POKEMON_CURRENT_STATS = "FIRST_POKEMON_CURRENT_STATS";
export const SECOND_POKEMON_CURRENT_STATS = "SECOND_POKEMON_CURRENT_STATS";
export const BATTLE_LOGS = "BATTLE_LOGS";
export const CLEAR_LOGS = "CLEAR_LOGS";